version: '3.9'

services:
  ac-database:
    ports:
      - "3307:3306"
    environment:
      TZ: ${TZ}

  ac-worldserver:
    environment:
      TZ: ${TZ}
    volumes:
      - ./modules:/azerothcore/modules:rw