services:
  ac-database:
    ports: !override
      - "3307:3307"
    environment:
      TZ: ${TZ}
      MYSQL_TCP_PORT: "3307"

  ac-authserver:
    environment:
      TZ: ${TZ}
      AC_LOGIN_DATABASE_INFO: "ac-database;3307;root;password;acore_auth"
    user: "1000:1000"

  ac-worldserver:
    environment:
      TZ: ${TZ}
      AC_CHARACTER_DATABASE_INFO: "ac-database;3307;root;password;acore_characters"
      AC_LOGIN_DATABASE_INFO: "ac-database;3307;root;password;acore_auth"
      AC_WORLD_DATABASE_INFO: "ac-database;3307;root;password;acore_world"
      AC_PLAYERBOTS_DATABASE_INFO: "ac-database;3307;root;password;acore_playerbots"
    volumes:
      - ./modules:/azerothcore/modules:rw
    user: "1000:1000"

  ac-db-import:
    environment:
      AC_CHARACTER_DATABASE_INFO: "ac-database;3307;root;password;acore_characters"
      AC_LOGIN_DATABASE_INFO: "ac-database;3307;root;password;acore_auth"
      AC_WORLD_DATABASE_INFO: "ac-database;3307;root;password;acore_world"
      AC_PLAYERBOTS_DATABASE_INFO: "ac-database;3307;root;password;acore_playerbots"
    user: "1000:1000"
