version: '3.9'              # ← Add version line

services:
  ac-database:
    ports:                  # ← Fix indentation (4 spaces)
      - "3307:3306"
    environment:
      TZ: ${TZ}

  ac-worldserver:
    environment:
      TZ: ${TZ}
    volumes:
      - ./modules:/azerothcore/modules:rw
